//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnaagdierenMarktGame.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HeaderResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HeaderResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KnaagdierenMarktGame.Client.Resources.HeaderResource", typeof(HeaderResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No timer set.
        /// </summary>
        public static string Auction_Bidding_DescriptionText {
            get {
                return ResourceManager.GetString("Auction_Bidding_DescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free bidding.
        /// </summary>
        public static string Auction_Bidding_SmallHeaderText {
            get {
                return ResourceManager.GetString("Auction_Bidding_SmallHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        public static string Auction_Countdown_DescriptionText {
            get {
                return ResourceManager.GetString("Auction_Countdown_DescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining time.
        /// </summary>
        public static string Auction_Countdown_SmallHeaderText {
            get {
                return ResourceManager.GetString("Auction_Countdown_SmallHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BuyOver_CurrentPlayer_DescriptionText {
            get {
                return ResourceManager.GetString("BuyOver_CurrentPlayer_DescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an animalcard and pay amount.
        /// </summary>
        public static string BuyOver_CurrentPlayer_SmallHeaderText {
            get {
                return ResourceManager.GetString("BuyOver_CurrentPlayer_SmallHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string BuyOver_Others_DescriptionText {
            get {
                return ResourceManager.GetString("BuyOver_Others_DescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is buying over.
        /// </summary>
        public static string BuyOver_Others_SmallHeaderText {
            get {
                return ResourceManager.GetString("BuyOver_Others_SmallHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ChooseAction_CurrentPlayer_DescriptionText {
            get {
                return ResourceManager.GetString("ChooseAction_CurrentPlayer_DescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ChooseAction_CurrentPlayer_SmallHeaderText {
            get {
                return ResourceManager.GetString("ChooseAction_CurrentPlayer_SmallHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an action.
        /// </summary>
        public static string ChooseAction_CurrentPlayer_Title {
            get {
                return ResourceManager.GetString("ChooseAction_CurrentPlayer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to may take some time.
        /// </summary>
        public static string ChooseAction_Others_DescriptionText {
            get {
                return ResourceManager.GetString("ChooseAction_Others_DescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is choosing.
        /// </summary>
        public static string ChooseAction_Others_SmallHeaderText {
            get {
                return ResourceManager.GetString("ChooseAction_Others_SmallHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting till action is chosen.
        /// </summary>
        public static string ChooseAction_Others_Title {
            get {
                return ResourceManager.GetString("ChooseAction_Others_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EndScreen_DescriptionText {
            get {
                return ResourceManager.GetString("EndScreen_DescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is the winner!.
        /// </summary>
        public static string EndScreen_SmallHeaderText {
            get {
                return ResourceManager.GetString("EndScreen_SmallHeaderText", resourceCulture);
            }
        }
    }
}
