//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnaagdierenMarktGame.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TestResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KnaagdierenMarktGame.Client.Resources.TestResource", typeof(TestResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIE.
        /// </summary>
        public static string Auction_BigHeaderText {
            get {
                return ResourceManager.GetString("Auction_BigHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mooi zo.
        /// </summary>
        public static string Auction_DescriptionText {
            get {
                return ResourceManager.GetString("Auction_DescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIEYEE.
        /// </summary>
        public static string Auction_SmallHeaderText {
            get {
                return ResourceManager.GetString("Auction_SmallHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TESTOSAURUS.
        /// </summary>
        public static string None__Auction__Trade {
            get {
                return ResourceManager.GetString("None, Auction, Trade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niets.
        /// </summary>
        public static string None_BigHeaderText {
            get {
                return ResourceManager.GetString("None_BigHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noppes.
        /// </summary>
        public static string None_DescriptionText {
            get {
                return ResourceManager.GetString("None_DescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nada.
        /// </summary>
        public static string None_SmallHeaderText {
            get {
                return ResourceManager.GetString("None_SmallHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UITKOPEN.
        /// </summary>
        public static string Trade_BigHeaderText {
            get {
                return ResourceManager.GetString("Trade_BigHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to als het goed gaat.
        /// </summary>
        public static string Trade_DescriptionText {
            get {
                return ResourceManager.GetString("Trade_DescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YESH.
        /// </summary>
        public static string Trade_SmallHeaderText {
            get {
                return ResourceManager.GetString("Trade_SmallHeaderText", resourceCulture);
            }
        }
    }
}
